### ISSUE TITLE
Implement notifications APIs

### ISSUE THREAD

**Issue by epiqueras** [kleros/kleros-api#49]
**Jurors:**

Notifications:
* Session started (register)/Able to activate tokens (automatically dismissed if not done manually by end of session)
* Drawn in dispute (we can handle this with a poll if we need too) `unfeasible right now since we can't iterate over a solidity mapping`
* ArbitrationFee collected
* Ruling took place
* Dispute appealed
* Appeal period over (PNK win/lose amount)

Pending Actions (Stateful):
* Dispute needs vote
* Dispute needs execution

**Contractors:**

Notifications:
* Dispute created
* Jurors drawn
* Ruling took place
* Dispute appealed
* Appeal period over (decision)

Pending Actions (Stateful):
* Outstanding fee
* Dispute pending repartition/execution

**Comment by satello** [comment]
Some edits to the list above

**Jurors**:

Event Notifications (updates can be pushed and are persisted)

- Ruling has been given
- Dispute Appealed (is this important to a juror?)
- PNK won/lost
- ArbitrationFee won

Stateful Notifications (poll for updates)

- Session started (is this useful?)
- Able to activate tokens
- Drawn in dispute (This one is tricky. It really belongs as an event notification but I don't see how we can do it. It is not possible to do via events so this is more or less a stateful notification as in the juror has to ask for their disputes at the correct period/session in order for us to know if they are drawn and we can't get past drawings. Still trying to figure out a better way for this one but I think it has to belong here for now)
- Needs vote (has to be in correct period/session to be able to vote)
- Dispute eligible for Repartition/Execute

**Contractor**

Event Notifications

- Dispute Created
- Ruling has been given/able to appeal
- Dispute resolved (final ruling)

Stateful Notifications

- Outstanding fee
- Dispute eligible for Repartition/Execute

**Comment by satello** [comment]
@epiqueras Here are my thoughts on the different notifications

**Comment by satello** [comment]
The `Drawn in dispute` notification is going to be a problem I think. It seems important that a juror should be pushed these notifications instead of logging in one day not knowing they were selected as juror in the last session and seeing that they lost tokens but have no way to know what from. We will have to keep thinking about that one

**Comment by epiqueras** [comment]
Some edits to the list above

**Jurors**:

Event Notifications (updates can be pushed and are persisted)

- Ruling has been given
- ArbitrationFee won
- Dispute Appealed (is this important to a juror?) `yes, this lets them know their tokens will be locked for longer.`
- PNK won/lost

Stateful Notifications (poll for updates)

- Session started (is this useful?) `It prompts users to activate tokens and register, but this should be an event notification since we only want it to show once per session and be dismissible.`
- Able to activate tokens `It's the same as session started.`
- Drawn in dispute (This one is tricky. It really belongs as an event notification but I don't see how we can do it. It is not possible to do via events so this is more or less a stateful notification as in the juror has to ask for their disputes at the correct period/session in order for us to know if they are drawn and we can't get past drawings. Still trying to figure out a better way for this one but I think it has to belong here for now) `we can still have it be an event notification. I think we can do it like this: fetch all the disputes for the current session, cross reference them to a list of dismissed disputes by disputeID for the current session, and only show the ones that are not in the dismissed list.`
- Needs vote (has to be in correct period/session to be able to vote)
- Dispute eligible for Repartition/Execute

**Contractor**

Event Notifications

- Dispute Created
`All jurors drawn (lets users know that jurors have started voting)`
- Ruling has been given/able to appeal
`Appealed (users need to know when the decision is appealed by the other party)`
- Dispute resolved (final ruling)

Stateful Notifications

- Outstanding fee
- Dispute eligible for Repartition/Execute

**Comment by epiqueras** [comment]
>The Drawn in dispute notification is going to be a problem I think. It seems important that a juror should be pushed these notifications instead of logging in one day not knowing they were selected as juror in the last session and seeing that they lost tokens but have no way to know what from. We will have to keep thinking about that one

The `PNK won/lost` notification can have information about the dispute it relates to, and since this notification is persisted, it will carry over to the next sessions until it is dismissed.

**Comment by epiqueras** [comment]
I updated the ticket.

**Comment by satello** [comment]
@epiqueras The more I look at things I still think `Activate Tokens` should be a stateful notification. In order to make it a "regular" notification we will need to allow jurors to subscribe to an arbitrator and then need to build special notification logic just to be able to overwrite the notification after the period changes or when they activate their tokens. Which then makes it behave exactly like a stateful notification but you can dismiss it. We can allow stateful notifications to be dismissed as well by storing dismissed notification `txHash`'s client side and not rendering those notifications. I am going to go ahead and make it stateful to start with

**Comment by epiqueras** [comment]
@satello 

Yes that sounds better. But can we store the txHash in the store? So the dismissal applies on multiple devices?

**Comment by satello** [comment]
@epiqueras Well the stateful notifications aren't in the store at all. We could make that work but it feels a bit hacky just for this one notification. Perhaps we can make that a different task for all stateful notifications if we decide we would like to be able to dismiss them. I don't see it being that big of a deal having an undismissable reminder that you can activate during a period since it is there for a relatively short period of time and is just telling you what you can do. How about we try it as undismissable to start and if we think UX would be better with making them dismissable make another task for that?

**Comment by satello** [comment]
Also the `AppealPossible` event is never triggered in `KlerosPOC` and I don't see where it can be. So we will not have that notification for now either. I will make another issue for getting that notification. We will probably have to do something a bit inefficient like iterating through all of the disputes and seeing which ones are appealable

**Comment by satello** [comment]
closed by https://github.com/kleros/kleros-api/pull/57
